const asciiArt = `
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                     ...                                                                                                                                                
                                                  .':loc.                                                                                                                                               
                                                 .:dOOx:'.                                              ........      ...                                                                               
                                               ..:x0Kkl'...                                           .......................                                                                           
                                            ...'lk0K0o,.....                                       ...................................                                                                  
                                      .........:xO0Oo;...................                      ........................................                                                                 
                                   ..','.......,lxOko;..... .................           .... ..........................................                                                                 
                                 ...'coc,,'''..,lxkko,'.......................      .................'',,,,''''.........................                                                                
                                ....,lddlc:;;,;ldkkxl;,'..........................................'',,,;;;;;,,,''''.....................                                                                
                               ....',:loddoolccok0XKOxdc;,......................................'',,,;;;:::::;;;,,'''''.......................                                                          
                               ...'';;;:ldkkkddx0NWWNXKkoc;,................................''''',,;;;;:::ccc:::;;,,'''''''''''''''............                                                         
                              ....,,;::cldk0K0O0XWWWWWNKkdc;'............................''',,,,,,;;;;:::ccllllc::;;,,,,,,,;;;;,,,''...........                                                         
                             ....',;:cloodkKNXXNWMMMMWWNXOdc;'..........................'',,;;;;;;:ccclloooodollcc:::::::::::::;;;,'...........                                                         
                              ...',;:lodxxkKNWWWMMMMMMMMWKxl:,,''..............''.......'',,;:::cccloodkOOkkkxolloollodolcccccc::;,'...                                                                 
                              ..',;:coxkkO00XWWMMMMMMMMMWKdl;;,,,,'''.........'''''''''',,,,;::clllooodkKNNNXKOkk000OOOkdllclcc::;,.... ....                                                            
                               ..,;:ldkO0XXXXWMMMMMMMMMMWXkl;,,,,,,,,,'''''...',,,,,,,,,,;;;::ccloooddx0XNNWWNXKXNWNXXKOxdollcc::;'...........               .............                              
                                 ...;dOKNWWWWWMMMMMMMMMWWNXkl,''''',,,,,,,,,,,,,;;;;;;;;,;;:cclloooddxOKXKXNWWWWWMMWWNXK0kxolccc:,.................       ...................                           
                                   .cOKNWMMMMMMMMMMMMMWWWNNX0d;'''''',,;;;;;,;;;:::;;;;;;;;:cloodddxxkO000XWWMMMMMMMWWWWNXOxolc:;'...............................',,''''.....                           
                                   ,xKNWMMMMMMMMMMMMMMWWWNNNXKOo;'''',,,,;;;;::::cc:::::::::clldddxxxkOOO0XWWWMMMMMMMMMMWNKkdoc;,................................',:cdxdc;..                            
                                 .,d0KNWMMMMMMMMMMMMMMWNXKXNNXX0kc,''''',,;;::ccccccccccclllllodddxkOOKK00XWWWMMMMMMMMMMWN0xoc;''''''''..........................';ld0NXd,.                             
                                .ck00KXNNWMMMMMMMMMMMMNKO0XWWNNKKOd:'.'',,;;::cccclllllloooooodddxkO0KWWXXNWWMMMMMMMMMMMNOo:;,'''''''''''''''....................';oxONK:.                              
                               .ck000OO0KNWWMMMMMMMMMMNK00XWWWNNX0Oko;..',,;;::ccllooooddddddddddxkO0XWWWWWWWMMMMMMMMMMMXo;,'',,,,'''''''''''''..........'''''''',;cxKNK:                               
                              .lO00OkkkOKNWWMMMMMMMMMMWX0KNWWWWNXX0Oko;'..',,;::cloooodddxxdddxxxxkOKXWMMMMWWMMMMMMMMMMW0c,,,,,,,,,,,,,,,,,,,''''''''',,,;,,,,,,;;:cxKKx;.                              
                             ,oO0OkkkkO0XNWMMMWMMMMMMWNK0KNWWWNNXK00Odl:;'..',,;:clooddxxxxxxxxkkkkO0KNWMMMWMMMMMMMMMWWNkl;;,,,,,,,,,,,,,,,,,,,,,,,,,,;;;:ooc:;:;:::cc;..                               
                           .;xOOOkkkOO0KNWMMMWWWMMMMWNKOOKNNWNNXXK0OOOkdl:'...'',;:clodxxxkkkkkkkkOO00KXNWWWWMMMMMMMMWXxc;,,,,,',,,,,,,,,,,,,,;;;;;;;::::cxXKxdxlc:,'...                                
                          .ckkkkkxkOOO0XWMMMMMMMMMMWWKkxkOO0XNXXKK0OOkkxdo:,.....'',:cldxxxkkkOOOOOOOOOkOKNNWMMMMMWWN0o:,''''''',,,,;;,,,,;;::c::::::cllod0NWXKXXOo,......                              
                         .lkkkxxxkkOOO0XNMMMMMMMMWWWW0odOK0OKXXK00OOkkxxddoc;'......',;:lodxxxxxkO0OOkkk0XNNWWWWWWMW0oc:;,'..',,,,,;;;;;;;:cccllllloooddkOXWWWWWW0:.......   ..           ..            
                        'okkxxxxxkkkO00XWMMMMMMMWWWWNx:o0X0k0KK00OOkkxxddoolc;,'.....'',,;:clol:lxkkkkxOKXXXXXXXNWWWOocc:;,..'',,,;;:::::cccccclloddxxkO0XNWMMMWXo..............                        
                      .;oxxxxxxxxkkkkO0KXNWWWWMMMMWWWOodOKOx0K00OOkxxddooolllc:,'.......'',;;:;,,;codxxkOOOOkOKNWWWXOdolc:;,'',;;;;:cccccccccccllodkO0KXNWWMMWNOl'.................                     
                     .;loodxxxxxxxxxkkOO0OO0XWMMMMMMWKddO0kdO0OOkkxxddoooollcc::;,'........''',,,'',;:odddxkkk0XNNN0kxdollc:;,,;;:::ccccllccllooddxk0XNWWMMWWNx:,,'..............             ......    
                    .':llodxddxxxxxxxkkOkddxkKWMMMMMWW0kOOdokOkkxxdddooollccc:::;;,'.........'''''''..',;coxxdxk0KK0Okkxddolc;,,;:clllllllllloodxkO0XNWMMMMWXxc;;,'.............               .........
                   .';:ldxxddddddxxdxxkkxooddkNMMMMMMWXkxxolxkkxxdddoolllcc:::::;;;,''........'''',,,'....',;:lodk000OOOkkxdol;,;cllooooooooddxxkO0XWMMMMMWXxc::;,'.............                ....... 
             ... ..;;;:oddooodddddddddxxxlclldKWMMMMMWKxxxllxxxdddooolllcc::;;;;,,,,,,''.....''''',,,,,;;,,'''',;:ldxO0OOkkxdol:;:clooooddddxxxkOKXWWMMMMWKxlccc:;'..............               ...     
       ...  .''. .';::clcclooooooooooddxdc:cld0WMMMMMM0doo:cddddoollccc:::;;;;,,,,,,,,,,'.........'',,,,;;::;;;;;;;;cxOOOOkkxddl::coodddddxxxdxOKNWMMMMMW0xooolc:;...............                       
       ..    .. .',';cc:::clllloooooooodo:::cd0NMMMMMW0lcc;:ooolllcccc:::;;;;,,,,,,',,,,,,'.. ...........',;;;;;::ccclodxxkkkxxdoccoddxddxxxxxO0XNWMMMMWXOxxdolc;;'. .............                      
              ......';;,,;:cccloooolllloc;,;lkXWMMMMWWOc:;,;lllllccc:::;;;,,,'''''..........     ...........''',,;;:::ccloodddxxxolldddxxdddxkO0KXXXNWWN0Okxdoc:;;'. ..............                     
              ....,;,,,'',,:ccllooollcll:,,,lONWMMMWNXd;,'';llllc::;;,,,,''..........             .................'',,;::clloodxxdoodxxxxxxxkkkxddxKNXK0Okxolc:;,'.  .............                     
             ....''',,'.'';:ccclllllccc:;''':xO00Okxol;....,;;;;,,,,,''''''.........                  .................'',;;::clodxxxO0OOkkxdoolc:cx0KK0Okxdolc:;,..  ............                      
            ....   ......',:ccccclllccc:,...';:::;;;;:;;;;;;;;;;;;;;,,''........                                     .......',:cloxOKNWNXK0xlcc:,;oO000Okxxolc:;;,..   ............                     
           ..'....     ..'',:cccccllccc:;'',,;:cclllllccc:;;,,,,''.......                                              ........';coOXXXKK00kdoc;,lxkOOkkxdollc:;'..    ............                     
            .....      ....';ccccc::;::::::ccllccc::;,,'''......                                                              .....,::colcc:;,'';ldxxxxxdollc;,'''..  ...........                       
   ....    .....      ......';;'......,:c::;;,,'.........                                          ...                         ........'.''.......',:ldoolc:;,',,'.................                     
            ..        ........     ..........                                                    ...............    ..........................   .'',cllc:;,,,,,''................                      
                                                                                                    ............................... ........... .':ccc::;,,,;,''...................                     
  ..                                              ............                                      ...............................  .......... ..,;;;,,,,,,,''''...................                    
....                                              ......                                               ........................ ..     ...........',,'''',''''''....................                    
                                                                                                             ..................             .   .....'',''''''''...................                     
                                                                                                               ..   ..........   .                 ....''''''......................                     
 ..                                                                                                            ..    .........                       ..'..........................                      
                                                                                                                     ..                            ....'.........................                       
                                                                                                                                          .........   ............................                      
                                                                                          ....                                             .........  ...........................                       
                                                                                          ..                                               .........  ......     .... ...........                       
                                                                                                                                 .         .........  ......     ...     .........                      
                                                                                                                                                       .....     ...     .. .....                       
                                                                                                                                                       .....     ...     .. .....                       
                                                                                                                                                       .....     ...     .........        ..            
                 .                                                                                                                                 .   .....     ...     ...................            
              ......                                                                                                            ..                 .   .....      ..     ...   ...................      
             ...                                                                                                               ....                ..  .....      ..      ....  ...          .......    
             ..                                                                                                               .....                ..  .....      ..      ..... ..                      
    ...  ...                                                                                                                 ......                ..  .. ..      ..      ........  ..                  

    `;

document.getElementById("asciiArt").textContent = asciiArt;
